echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf scatterd.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf scatterd/__pycache__
rm -rf scatterd/.pylint.d
rm -rf tests/__pycache__
rm -rf scatterd/utils/__pycache__
rm -rf .pylint.d
rm -rf scatterd/data/*.zip
rm -rf scatterd/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
